version: '3.3'

services:

  fpm:
    image: flole/php71-docker-development:latest
    volumes:
      - ./:/srv/htdocs
      - ./node_modules:/srv/htdocs/node_modules:cached
      - ./vendor:/srv/htdocs/vendor:cached
    depends_on:
      - postgres
      - node
      - selenium
    environment:
      - COVERALLS_RUN_LOCALLY
      - COVERALLS_REPO_TOKEN

  nginx:
    image: nginx:latest
    depends_on:
      - fpm
    ports:
      - "8889:80"
    volumes:
      - ./.docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/htdocs
      - ./node_modules:/srv/htdocs/node_modules:cached
      - ./vendor:/srv/htdocs/vendor:cached

  node:
    image: node:6.11.2
    volumes:
      - ./:/srv/htdocs
      - ./node_modules:/srv/htdocs/node_modules:cached
      - ./vendor:/srv/htdocs/vendor:cached
    working_dir: /srv/htdocs
    tty: true

  # mysql server
  postgres:
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - "8885:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgres

  selenium:
    image: selenium/standalone-chrome